
/tof_sensor:
    sensor_uri: /dev/ttyACM0
    flip_horizontal: false
    flip_vertical: false
    stream_type: distance_amplitude

/tof_sensor_2:
    sensor_uri: /dev/ttyACM2
    flip_horizontal: false
    flip_vertical: false
    stream_type: distance_amplitude

/tf:
  x: 0
  y: 0
  z: 0
  qx: 0
  qy: 0
  qz: 0
  qw: 0
  frame_id: base_footprint
  child_frame_id: /dev/ttyACM0
  period_in_ms: 100        
  
/tf_2:
  x: 5
  y: 0
  z: 0
  yaw: 0
  pitch: 0
  roll: 0
  destination: base_footprint
  source: /dev/ttyACM2
